package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/authz"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/pkg/xtime"
	"github.com/looplj/axonhub/internal/scopes"
	"github.com/samber/lo"
)

// AnalyticsMetadata is the resolver for the analyticsMetadata field.
func (r *queryResolver) AnalyticsMetadata(ctx context.Context) (*AnalyticsMetadata, error) {
	if err := authz.RequireSystemScope(ctx, scopes.ScopeReadDashboard); err != nil {
		return nil, err
	}

	scopeCtx := authz.WithSystemScopeDecision(ctx, scopes.ScopeReadDashboard)
	loc := r.systemService.TimeLocation(ctx)

	// Find earliest created_at
	first, err := r.productionUsageLogQuery().Order(ent.Asc(usagelog.FieldCreatedAt)).First(scopeCtx)
	if err != nil {
		if ent.IsNotFound(err) {
			return &AnalyticsMetadata{}, nil
		}

		return nil, err
	}

	d := first.CreatedAt.In(loc).Format("2006-01-02")
	return &AnalyticsMetadata{EarliestDate: &d}, nil
}

// AnalyticsOverview is the resolver for the analyticsOverview field.
func (r *queryResolver) AnalyticsOverview(ctx context.Context, filter *AnalyticsFilter) (*AnalyticsOverview, error) {
	if err := authz.RequireSystemScope(ctx, scopes.ScopeReadDashboard); err != nil {
		return nil, err
	}
	if err := validateAnalyticsFilterScopes(ctx, filter); err != nil {
		return nil, err
	}
	loc := r.systemService.TimeLocation(ctx)
	dateRange, err := resolveAnalyticsDateRange(filter, loc, xtime.UTCNow())
	if err != nil {
		return nil, err
	}

	type overviewResult struct {
		TotalRequests     int     `json:"total_requests"`
		TotalInputTokens  int64   `json:"total_input_tokens"`
		TotalCachedTokens int64   `json:"total_cached_tokens"`
		TotalOutputTokens int64   `json:"total_output_tokens"`
		TotalTokens       int64   `json:"total_tokens"`
		TotalCost         float64 `json:"total_cost"`
	}

	var results []overviewResult

	scopeCtx := authz.WithSystemScopeDecision(ctx, scopes.ScopeReadDashboard)
	err = r.productionUsageLogQuery().
		Modify(func(s *sql.Selector) {
			r.buildAnalyticsWhere(s, filter, dateRange)

			s.Select(
				sql.As(sql.Count(s.C(usagelog.FieldID)), "total_requests"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptTokens)), "total_input_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptCachedTokens)), "total_cached_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldCompletionTokens)), "total_output_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldTotalTokens)), "total_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldTotalCost)), "total_cost"),
			)
		}).
		Scan(scopeCtx, &results)
	if err != nil {
		return nil, fmt.Errorf("failed to get analytics overview: %w", err)
	}

	if len(results) == 0 {
		return &AnalyticsOverview{}, nil
	}

	r0 := results[0]
	return &AnalyticsOverview{
		TotalTokens:              safeIntFromInt64(r0.TotalTokens),
		TotalInputTokens:         safeIntFromInt64(r0.TotalInputTokens),
		TotalCachedInputTokens:   safeIntFromInt64(r0.TotalCachedTokens),
		TotalUncachedInputTokens: safeIntFromInt64(r0.TotalInputTokens - r0.TotalCachedTokens),
		TotalOutputTokens:        safeIntFromInt64(r0.TotalOutputTokens),
		TotalRequests:            r0.TotalRequests,
		TotalCost:                r0.TotalCost,
	}, nil
}

// AnalyticsDailyStats is the resolver for the analyticsDailyStats field.
func (r *queryResolver) AnalyticsDailyStats(ctx context.Context, filter *AnalyticsFilter) ([]*AnalyticsDailyStat, error) {
	if err := authz.RequireSystemScope(ctx, scopes.ScopeReadDashboard); err != nil {
		return nil, err
	}
	if err := validateAnalyticsFilterScopes(ctx, filter); err != nil {
		return nil, err
	}
	loc := r.systemService.TimeLocation(ctx)
	dateRange, err := resolveAnalyticsDateRange(filter, loc, xtime.UTCNow())
	if err != nil {
		return nil, err
	}

	type dailyStats struct {
		Date         string  `json:"date"`
		InputTokens  int64   `json:"input_tokens"`
		CachedTokens int64   `json:"cached_tokens"`
		OutputTokens int64   `json:"output_tokens"`
		TotalTokens  int64   `json:"total_tokens"`
		RequestCount int     `json:"request_count"`
		Cost         float64 `json:"cost"`
	}

	var results []dailyStats

	scopeCtx := authz.WithSystemScopeDecision(ctx, scopes.ScopeReadDashboard)
	err = r.productionUsageLogQuery().
		Modify(func(s *sql.Selector) {
			r.buildAnalyticsWhere(s, filter, dateRange)

			createdAtCol := s.C(usagelog.FieldCreatedAt)
			dateExpr := analyticsDateExpression(s.Dialect(), createdAtCol, dateRange, loc)

			s.Select(
				sql.As(dateExpr, "date"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptTokens)), "input_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldPromptCachedTokens)), "cached_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldCompletionTokens)), "output_tokens"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldTotalTokens)), "total_tokens"),
				sql.As(sql.Count(s.C(usagelog.FieldID)), "request_count"),
				sql.As(fmt.Sprintf("COALESCE(SUM(%s), 0)", s.C(usagelog.FieldTotalCost)), "cost"),
			).
				GroupBy(dateExpr).
				OrderBy("date")
		}).
		Scan(scopeCtx, &results)
	if err != nil {
		return nil, fmt.Errorf("failed to get analytics daily stats: %w", err)
	}

	// Build lookup map
	statsMap := lo.SliceToMap(results, func(item dailyStats) (string, dailyStats) {
		return item.Date, item
	})

	// Fill in missing dates with zero values
	response := make([]*AnalyticsDailyStat, 0, defaultAnalyticsRangeDays)
	for d := dateRange.startDay; !d.After(dateRange.endDay); d = d.AddDate(0, 0, 1) {
		dateStr := d.Format("2006-01-02")

		if stats, exists := statsMap[dateStr]; exists {
			response = append(response, &AnalyticsDailyStat{
				Date:                dateStr,
				InputTokens:         safeIntFromInt64(stats.InputTokens),
				CachedInputTokens:   safeIntFromInt64(stats.CachedTokens),
				UncachedInputTokens: safeIntFromInt64(stats.InputTokens - stats.CachedTokens),
				OutputTokens:        safeIntFromInt64(stats.OutputTokens),
				TotalTokens:         safeIntFromInt64(stats.TotalTokens),
				RequestCount:        stats.RequestCount,
				Cost:                stats.Cost,
			})
		} else {
			response = append(response, &AnalyticsDailyStat{
				Date:                dateStr,
				InputTokens:         0,
				CachedInputTokens:   0,
				UncachedInputTokens: 0,
				OutputTokens:        0,
				TotalTokens:         0,
				RequestCount:        0,
				Cost:                0,
			})
		}
	}

	return response, nil
}

// AnalyticsFilterOptions is the resolver for the analyticsFilterOptions field.
func (r *queryResolver) AnalyticsFilterOptions(ctx context.Context, dimension AnalyticsFilterDimension, search *string, first *int, startTime *string, endTime *string) ([]*AnalyticsFilterOption, error) {
	if err := authz.RequireSystemScope(ctx, scopes.ScopeReadDashboard); err != nil {
		return nil, err
	}

	limit, err := resolveAnalyticsLimit(first, defaultAnalyticsOptionSize, maxAnalyticsOptionSize)
	if err != nil {
		return nil, err
	}

	dateFilter := &AnalyticsFilter{StartTime: startTime, EndTime: endTime}
	if startTime == nil && endTime == nil {
		dateFilter = nil
	}

	return r.queryAnalyticsFilterOptions(ctx, dateFilter, dimension, search, limit)
}

// AnalyticsDimensionStats is the resolver for the analyticsDimensionStats field.
func (r *queryResolver) AnalyticsDimensionStats(ctx context.Context, filter *AnalyticsFilter, dimension AnalyticsDimension, first *int) ([]*AnalyticsDimensionStat, error) {
	if err := authz.RequireSystemScope(ctx, scopes.ScopeReadDashboard); err != nil {
		return nil, err
	}
	if err := validateAnalyticsFilterScopes(ctx, filter); err != nil {
		return nil, err
	}

	requiredScope := scopes.ScopeReadDashboard
	switch dimension {
	case AnalyticsDimensionChannel:
		requiredScope = scopes.ScopeReadChannels
	case AnalyticsDimensionAPIKey:
		requiredScope = scopes.ScopeReadAPIKeys
	case AnalyticsDimensionUser:
		requiredScope = scopes.ScopeReadUsers
	case AnalyticsDimensionModel:
	default:
		return nil, fmt.Errorf("unsupported analytics dimension: %s", dimension)
	}
	if err := authz.RequireSystemScope(ctx, requiredScope); err != nil {
		return nil, err
	}

	limit, err := resolveAnalyticsLimit(first, defaultAnalyticsDimensionSize, maxAnalyticsDimensionSize)
	if err != nil {
		return nil, err
	}

	dateRange, err := resolveAnalyticsDateRange(filter, r.systemService.TimeLocation(ctx), xtime.UTCNow())
	if err != nil {
		return nil, err
	}

	var (
		results  []dimStats
		queryErr error
	)

	switch dimension {
	case AnalyticsDimensionChannel:
		results, queryErr = r.queryChannelStats(ctx, filter, dateRange, limit)
	case AnalyticsDimensionModel:
		results, queryErr = r.queryModelStats(ctx, filter, dateRange, limit)
	case AnalyticsDimensionAPIKey:
		results, queryErr = r.queryAPIKeyStats(ctx, filter, dateRange, limit)
	case AnalyticsDimensionUser:
		results, queryErr = r.queryUserStats(ctx, filter, dateRange, limit)
	}

	if queryErr != nil {
		return nil, queryErr
	}

	return dimStatsToDimensionStats(results), nil
}
